version: "3.9"

services:
    packet_analyzer:
        container_name: packet_analyzer
        image: packet_analyzer
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: app
        volumes:
            - ./logs:/var/log/nginx
        environment:
            DOCKER: "true"
        expose:
            - "${PORT}"
        networks:
            - docker

networks:
    docker:
        external: true
